repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Укажите последнюю версию Ruff, чтобы использовать все новые возможности
    rev: v0.5.0
    hooks:
        # Этот хук будет запускать линтер и автоматически исправлять ошибки
      - id: ruff
        args: [--fix]
        # Этот хук будет форматировать код
      - id: ruff-format