[tool.ruff]
# Ставим стандартную длину строки, как у Black
line-length = 88
# Указываем версию Python для предложений по улучшению синтаксиса
target-version = "py311"

exclude = ["*/migrations/*.py"]

[tool.ruff.lint]
# Выбираем наборы правил для проверки:
# E, W -> стандартные ошибки и предупреждения PEP 8
# F -> ошибки Pyflakes (неиспользуемые переменные и т.д.)
# I -> сортировка импортов (как isort)
# B -> flake8-bugbear (потенциальные баги)
# UP -> pyupgrade (модернизация синтаксиса)
select = ["E", "W", "F", "I", "B", "UP"]

# Здесь можно добавить коды правил для игнорирования, если нужно
ignore = ["E501"] # Игнорируем ошибку длины строки, т.к. ее исправит форматер

[tool.ruff.lint.isort]
# Сообщаем Ruff о папках с вашим кодом для правильной группировки импортов.
# Укажите здесь папки ваших приложений.
known-first-party = ["DjangoProject", "user", "task"]

[tool.ruff.format]
# Настройки, совместимые с Black
quote-style = "double"