# Generated by Django 5.2 on 2025-04-14 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_at"]},
        ),
    ]
